curriculo/urls.py
from django.urls import path

from . import views

app_name = 'curriculo'

urlpatterns = [
    path('list', views.CurriculoListView.as_view(), name='list'),
    path('user_profile/<username>', views.get_user_profile, name='user_profile'),
    path('profile/<int:curriculo_id>/', views.curriculo_detail, name='profile'),
    path('update/<int:curriculo_id>/', views.update_curriculo, name='update'),
    path('search/', views.search_curriculo, name='search'),
]

poliempregos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('propostas/', include('propostas.urls')),
    path('noticias/', include('noticias.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('curriculo/', include('curriculo.urls'))
]

user/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path('registration', registration,name='registration'),
    path('signup/',SignUp,name='signup'),
    path('signup/estudante', EstudanteSignUpView.as_view(), name='estudante_signup'),
    path('signup/empresa', EmpresaSignUpView.as_view(), name='empresa_signup'),
]

curriculo/models.py
from django.db import models
from django.conf import settings
from user.models import Estudante

class Curso(models.Model):
    descricao = models.CharField(max_length=255,null=True)

    def __str__(self):
        return f'"{self.descricao}"'

class Curriculo(models.Model):
    estudante = models.OneToOneField(Estudante,on_delete=models.CASCADE)
    curso = models.ForeignKey(Curso,on_delete=models.CASCADE,null=True)
    bio = models.TextField(null=True)
    foto = models.URLField(max_length=200, null=True)
    profissional = models.TextField(null=True)
    academico = models.TextField(null=True)
    experiencia = models.TextField(null=True)

    def __str__(self):
        return f'"{self.estudante}"'

curriculo/forms.py
from django import forms
from .models import Curso, Curriculo
from user.models import User, Estudante

class UserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']

class CurriculoForm(forms.Form):
    curso = forms.ModelChoiceField(queryset = Curso.objects.all())
    bio = forms.CharField(widget=forms.Textarea())
    foto = forms.URLField(max_length=200)
    profissional = forms.CharField(widget=forms.Textarea())
    academico = forms.CharField(widget=forms.Textarea())
    experiencia = forms.CharField(widget=forms.Textarea())
    #class Meta:
        #model = Curriculo
        #fields = [
         #   'bio',
         #   'foto',
         #   'profissional',
          #   'experiencia',
       # ]
        #labels = {
        #    'bio':'BIO',
       #     'foto':'URL da Foto',
       #     'profissional':'Profissional',
      #      'academico':'Acadêmico',
       #     'experiencia':'Experiência',
       # }

class CursoForm(forms.Form):
    class Meta:
        model = Curso
        fields = [
            'descricao',
        ]
        labels = {
            'descricao':'Curso',
        }

curriculo/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied

from .models import Curso, Curriculo
from .forms import CursoForm, CurriculoForm
from user.models import User, Estudante

# CURRICULO #
@login_required
def curriculo_detail(request, curriculo_id):
    #estudante = request.user.estudante
   curriculo = get_object_or_404(Curriculo, pk=curriculo_id)
   context = {'curriculo': curriculo}
    #curriculo_detail = get_object_or_404(Curriculo, estudante=estudante)
   return render(request, 'curriculo/profile.html', context)  #,'estudante': estudante})

@login_required
def get_user_profile(request,username):
    user = User.objects.get(username=username)
    curriculo = Curriculo.objects.get(estudante=user.estudante) 
    return render(request, 'curriculo/user_profile.html', {"user":user, 'curriculo': curriculo})

class CurriculoListView(generic.ListView,LoginRequiredMixin):
    model = Curriculo
    template_name = 'curriculo/list.html'

@login_required
def search_curriculo(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query']
        curriculo_list = Curriculo.objects.filter(estudante__name__icontains=search_term)
        context = {"curriculo_list": curriculo_list}

    return render(request, 'curriculo/search.html', context)

@login_required
@permission_required('curriculo.change_curriculo')
def update_curriculo(request, curriculo_id):

    curriculo = get_object_or_404(Curriculo, pk=curriculo_id)
    #Restringir edição ao dono do curriculo.
    if not (curriculo.estudante == request.user.estudante or request.user.is_superuser):
        raise PermissionDenied

    if request.method == "POST":

        form = CurriculoForm(request.POST)

        if form.is_valid():
            curriculo.curso = form.cleaned_data['curso']
            curriculo.bio = form.cleaned_data['bio']
            curriculo.foto = form.cleaned_data['foto']
            curriculo.profissional = form.cleaned_data['profissional']
            curriculo.academico = form.cleaned_data['academico']
            curriculo.experiencia = form.cleaned_data['experiencia']
            curriculo.save()
            return HttpResponseRedirect(
                reverse('curriculo:profile', args=(curriculo.id, )))

    else:
        form = CurriculoForm(
            initial={
                'curso': curriculo.curso,
                'bio': curriculo.bio,
                'foto': curriculo.foto,
                'profissional': curriculo.profissional,
                'academico': curriculo.academico,
                'experiencia': curriculo.experiencia
            })

    context = {'curriculo': curriculo, 'form': form}
    return render(request, 'curriculo/update.html', context)

# CURSO #

curriculo/templates/curriculo/detail.html
{% extends "base.html" %}

{% block content %}
    <div>
        <img src="{{ curriculo_detail.foto }}" alt="Nome de Estudante {{ curriculo_detail.estudante}}">
        <h1>Curriculo de {{curriculo_detail.estudante}}</h1>
    </div>

    <div class="container">
        <div class="p-5 text-white bg-dark rounded-3 container">
            <p>Curso: {{curriculo_detail.curso}}</p>
            <hr>
            <p>Bio: {{curriculo_detail.bio}}</p>
            <hr>
            <p>Experiência Profissional: {{curriculo_detail.profissional}}</p>
            <hr>
            <p>Experiência Acadêmica: {{curriculo_detail.academico}}</p>
            <hr> 
            <p> Outras Experiência: {{curriculo_detail.experiencia}}</p>
        </div>
    </div>
{% endblock %}

curriculo/templates/curriculo/list.html
{% extends "base.html" %}

{% block content %}

{% if curriculo_list %}
<div class="curriculo-list-top">
    <a class= 'button' href="{% url 'curriculo:search' %}">Buscar Currículo</a>
    {% if request.user.is_estudante == True %} 
    <a class= 'button' href="{% url 'curriculo:user_profile' user.username %}">Meu Curriculo</a>
    {% endif %}
</div>

<section class="lista-de-cards">

    {% for curriculo in curriculo_list %}

    <article class="curriculo-card">
        {% if curriculo.foto %}
        <img class= 'retrato' src="{{ curriculo.foto }}" alt="Nome de Estudante {{ curriculo.estudante}}" width="180" height="180">
        {% endif %}
        <div class="curriculo-text"> 
            <a class = 'curriculo-name' href="{% url 'curriculo:profile' curriculo.id %}">{{ curriculo.estudante.name }}</a>
            {% if curriculo.bio %}
            <p class = 'curriculo-bio'>{{ curriculo.bio }}</p>
            {% endif %}
        </div>
    </article>

    {% endfor %}
</section>

{% else %}
<p>Não foi encontrado nenhum currículo.</p>

{% endif %}

{% endblock content %}

curriculo/templates/curriculo/profile.html
{% extends 'base.html' %}

{% block content %}
<br>
  <div class = "profile">
    <div class = "profile-top">
      {% if curriculo.foto %}
      <img class="retrato" src="{{ curriculo.foto }}" alt="{{ curriculo.estudante }}" width="350" height="350">
      {% else %}
      <p class="sem-foto">Sem foto</p>
      {% endif %}
      <div class = "profile-topright">
        <h2>{{ curriculo.estudante.name }}</h2>
        {% if curriculo.bio %}
        <p class="profile-bio"><b>Bio:</b> {{ curriculo.bio }}</p>
        {% else %}
        <p><b>Bio:</b></p>
        {% endif %}

        <p class="contato"><b>Contato:</b> {{ curriculo.estudante.user.email }}</p>
        <div class="edit-profile">
          {% if curriculo.curso %}
          <p class="card-text"><b>Curso:</b> {{ curriculo.curso }}</p>
          {% else %}
          <p class="card-text"><b>Curso:</b></p>
          {% endif %}
          {% if curriculo.estudante == request.user.estudante %}
          <a class = "button" href="{% url 'curriculo:update' curriculo.id %}">Editar</a>
         {% endif %}
        </div>
      </div>
    </div>
    <hr>
    <div class="card-body col-9">
      {% if curriculo.profissional %}
      <p class="card-text"><b>Experiência Profissional:</b> {{ curriculo.profissional }}</p>
      {% else %}
      <p class="card-text"><b>Experiência Profissional:</b></p>
      {% endif %}
      <hr>
      {% if curriculo.profissional %}
      <p class="card-text"><b>Experiência Acadêmica:</b> {{ curriculo.academico }}</p>
      {% else %}
      <p class="card-text"><b>Experiência Acadêmica:</b></p>
      {% endif %}
      <hr>
      {% if curriculo.profissional %}
      <p class="card-text"><b>Outras Experiências:</b> {{ curriculo.experiencia }}</p>
      {% else %}
      <p class="card-text"><b>Outras Experiências:</b></p>
      {% endif %}
    </div>
  </div>
{% endblock %}

curriculo/templates/curriculo/search.html
{% extends 'base.html' %}


{% block content %}
<div class="pesquisa-curriculo">
    <h2>Pesquisa de Currículo por Nome</h2>

<form action="{% url 'curriculo:search' %}">

    <p>

        <label for="id_query">Título:</label>

        <input type="text" name="query" id="id_query" />

    </p>

    <button type="submit">Buscar</button>

</form>





{% if curriculo_list %}
<h2>Resultado da Busca</h2>
<section class="lista-de-cards">

    {% for curriculo in curriculo_list %}

    <article class="curriculo-card">
        <img class= 'retrato' src="{{ curriculo.foto }}" alt="Nome de Estudante {{ curriculo.estudante}}" width="180" height="180">
        <div class="curriculo-text"> 
            <a class = 'curriculo-name' href="{% url 'curriculo:profile' curriculo.id %}">{{ curriculo.estudante.name }}</a>
            <p class = 'curriculo-bio'>{{ curriculo.bio }}</p>
        </div>
    </article>

    {% endfor %}

</section>

{% else %}
<p>Não foi encontrado nenhum currículo para a busca.</p>

{% endif %}

</div>
{% endblock content %}

curriculo/templates/curriculo/update.html
{% extends 'base.html' %}


{% block content %}
<div class="formulario-top">
    <h2>Atualizar Currículo</h2>
</div>
<div class="formulario">
    <div class="formulario" style="text-align: center;border-style: solid;border-width: 8px;border-color: #002292; width:65%;">
        <p>
            <div class="formulario">
                <form method="POST" accept-charset="utf-8">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Atualizar</button>
                    
                </form>
            </div>
        </p>
    </dv>
</div>

{% endblock %}

curriculo/templates/curriculo/user_profile.html
{% extends 'base.html' %}

{% block content %}
<br>
  <div class = "profile">
    <div class = "profile-top">
      {% if curriculo.foto %}
      <img class="retrato" src="{{ curriculo.foto }}" alt="{{ curriculo.estudante }}" width="350" height="350">
      {% else %}
      <p class="sem-foto">Sem foto</p>
      {% endif %}
      <div class = "profile-topright">
        <h2>{{ curriculo.estudante.name }}</h2>
        {% if curriculo.bio %}
        <p class="profile-bio"><b>Bio:</b> {{ curriculo.bio }}</p>
        {% else %}
        <p><b>Bio:</b></p>
        {% endif %}

        <p class="contato"><b>Contato:</b> {{ request.user.email }}</p>
        <div class="edit-profile">
          {% if curriculo.curso %}
          <p class="card-text"><b>Curso:</b> {{ curriculo.curso }}</p>
          {% else %}
          <p class="card-text"><b>Curso:</b></p>
          {% endif %}
          {% if curriculo.estudante == request.user.estudante %}
          <a class = "button" href="{% url 'curriculo:update' curriculo.id %}">Editar</a>
         {% endif %}
        </div>
      </div>
    </div>
    <hr>
    <div class="card-body col-9">
      {% if curriculo.profissional %}
      <p class="card-text"><b>Experiência Profissional:</b> {{ curriculo.profissional }}</p>
      {% else %}
      <p class="card-text"><b>Experiência Profissional:</b></p>
      {% endif %}
      <hr>
      {% if curriculo.profissional %}
      <p class="card-text"><b>Experiência Acadêmica:</b> {{ curriculo.academico }}</p>
      {% else %}
      <p class="card-text"><b>Experiência Acadêmica:</b></p>
      {% endif %}
      <hr>
      {% if curriculo.profissional %}
      <p class="card-text"><b>Outras Experiências:</b> {{ curriculo.experiencia }}</p>
      {% else %}
      <p class="card-text"><b>Outras Experiências:</b></p>
      {% endif %}
    </div>
  </div>
{% endblock %}