curriculo/urls.py
from django.urls import path

from . import views

app_name = 'curriculo'

urlpatterns = [
    path('list', views.CurriculoListView.as_view(), name='list'),
    path('user_profile/<username>', views.get_user_profile, name='user_profile'),
    path('profile/<int:curriculo_id>/', views.curriculo_detail, name='profile'),
    path('update/<int:curriculo_id>/', views.update_curriculo, name='update'),
    path('search/', views.search_curriculo, name='search'),
]

noticias/urls.py
from django.urls import path

from . import views

app_name = 'noticias'
urlpatterns = [
    path('', views.list_noticias, name='index'),
    path('search/', views.search_noticias, name='search'),
    path('create/', views.create_noticia, name='create'),
    path('<int:noticia_id>/', views.detail_noticia, name='detail'),
    path('update/<int:noticia_id>/', views.update_noticia, name='update'),
    path('delete/<int:noticia_id>/', views.delete_noticia, name='delete'),
    path('<int:noticia_id>/comment/', views.create_comment, name='comment'),
]

poliempregos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('propostas/', include('propostas.urls')),
    path('noticias/', include('noticias.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('curriculo/', include('curriculo.urls'))
]

user/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path('registration', registration,name='registration'),
    path('signup/',SignUp,name='signup'),
    path('signup/estudante', EstudanteSignUpView.as_view(), name='estudante_signup'),
    path('signup/empresa', EmpresaSignUpView.as_view(), name='empresa_signup'),
]

noticias/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class Noticia(models.Model):
    name = models.CharField(max_length=255) 
    release_date  = models.DateTimeField(default=timezone.now)
    descricao = models.TextField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.release_date})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

noticias/forms.py
from django.forms import ModelForm
from .models import Noticia, Comment


class NoticiaForm(ModelForm):
    class Meta:
        model = Noticia
        fields = [
            'name',
            'descricao',
            'poster_url',
        ]
        labels = {
            'name': 'Título da notícia',
            'descricao': 'Descrição',
            'poster_url': 'URL da imagem',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'text',
        ]
        labels = {
            'text': 'Comentário',
        }

noticias/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Noticia
from django.urls import reverse
from .models import Noticia, Comment
from .forms import NoticiaForm, CommentForm
from django.contrib.auth.decorators import login_required, permission_required

@login_required
def detail_noticia(request, noticia_id):
    noticia = get_object_or_404(Noticia, pk=noticia_id)
    context = {'noticia': noticia}
    return render(request, 'noticias/detail.html', context)

@login_required
def list_noticias(request):
    noticia_list = Noticia.objects.all()
    context = {'noticia_list': noticia_list}
    return render(request, 'noticias/index.html', context)

@login_required
def search_noticias(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        noticia_list = Noticia.objects.filter(name__icontains=search_term)
        context = {"noticia_list": noticia_list}
    return render(request, 'noticias/search.html', context)

@login_required
@permission_required('noticia.add_noticia')
def create_noticia(request):
    if request.method == 'POST':
        form = NoticiaForm(request.POST)
        if form.is_valid():
            noticia_name = form.cleaned_data['name']
            noticia_descricao = form.cleaned_data['descricao']
            noticia_poster_url = form.cleaned_data['poster_url']
            noticia = Noticia(name=noticia_name,
                          descricao=noticia_descricao,
                          poster_url=noticia_poster_url)
            noticia.save()
            return HttpResponseRedirect(
                reverse('noticias:detail', args=(noticia.id, )))
    else:
        form = NoticiaForm()
    context = {'form': form}
    return render(request, 'noticias/create.html', context)

@login_required
@permission_required('noticia.change_noticia')
def update_noticia(request, noticia_id):
    noticia = get_object_or_404(Noticia, pk=noticia_id)

    if request.method == "POST":
        form = NoticiaForm(request.POST)
        if form.is_valid():
            noticia.name = form.cleaned_data['name']
            noticia.descricao = form.cleaned_data['descricao']
            noticia.poster_url = form.cleaned_data['poster_url']
            noticia.save()
            return HttpResponseRedirect(
                reverse('noticias:detail', args=(noticia.id, )))
    else:
        form = NoticiaForm(
            initial={
                'name': noticia.name,
                'descricao': noticia.descricao,
                'poster_url': noticia.poster_url
            })

    context = {'noticia': noticia, 'form': form}
    return render(request, 'noticias/update.html', context)

@login_required
@permission_required('noticia.delete_noticia')
def delete_noticia(request, noticia_id):
    noticia = get_object_or_404(Noticia, pk=noticia_id)

    if request.method == "POST":
        noticia.delete()
        return HttpResponseRedirect(reverse('noticias:index'))

    context = {'noticia': noticia}
    return render(request, 'noticias/delete.html', context)

@login_required
def create_comment(request, noticia_id):
    noticia = get_object_or_404(Noticia, pk=noticia_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = request.user
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            noticia = noticia)
            comment.save()
            return HttpResponseRedirect(
                reverse('noticias:detail', args=(noticia_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'noticia': noticia}
    return render(request, 'noticias/comment.html', context)

noticias/templates/noticias/comment.html
{% extends 'base.html' %}

{% block title %}
Comentar notícia
{% endblock title %}

{% block content %}
<h2>Comentar a notícia {{ noticia.name }} ({{ noticia.release_date | date }})</h2>

<form action="{% url 'noticias:comment' noticia.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentário</button>
</form>

<p><a href="{% url 'noticias:detail' noticia.id %}">Voltar para a página da notícia</a></p>
{% endblock content %}

noticias/templates/noticias/create.html
{% extends 'base.html' %}


{% block content %}
<hr>
<h2>Inserir Nova Notícia</h2>

<form method="POST" action="{% url 'noticias:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

noticias/templates/noticias/delete.html
{% extends 'base.html' %}

{% block title %}
Deletar notícia
{% endblock title %}

{% block content %}
<form action="{% url 'noticias:delete' noticia.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a notícia "{{ noticia.name }} ({{ noticia.release_date | date }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

noticias/templates/noticias/detail.html
{% extends 'base.html' %}

{% block title %}
{{ noticia.name }} ({{ noticia.release_date | date}}
{% endblock title %}

{% block content %}
<hr>
<h2>{{ noticia.name }} ({{ noticia.release_date | date }})</h2>

<section class="dados-de-filme">
    <center>
        <img src="{{ noticia.poster_url }}" alt="Poster da notícia {{ noticia.name}}" height="300px" width="300px">
    </center>

    <center style="font-weight: bold;">
        {{ noticia.name }}
    </center>
    <p align="justify"> {{ noticia.descricao }}</p>
    <p align="right"><i>Data de publicação: {{ noticia.release_date | date }}</i></p>
    <ul>                
        {% if not request.user.is_estudante %}
        {% if not request.user.is_empresa %}
        <div class="proposta-list-top">
            <a class = 'button' href="{% url 'noticias:update' noticia.id %}">Editar</a>
            <a class = 'button' href="{% url 'noticias:delete' noticia.id %}">Apagar</a>
        </div>
           
        {% endif %}
        {% endif %}
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if noticia.comment_set.all %}
            {% for comment in noticia.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>Autor: {{ comment.author }}
                </figure>
                <hr>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para esta notícia.</p>
        {% endif %}
    </ul>
    <a href="{% url 'noticias:comment' noticia.pk %}"><button>Faça seu comentário</button></a>
</section>

{% endblock content %}

noticias/templates/noticias/index.html
{% extends 'base.html' %}

{% block title %}
Notícias
{% endblock title %}

{% block content %}
<section class="curriculo-list-top">
    <a class = 'button' href="{% url 'noticias:search' %}">Buscar Notícias</a>

    {% if not request.user.is_estudante %}
    {% if not request.user.is_empresa %}
        <a class = 'button' href="{% url 'noticias:create' %}">Adicionar Nova Notícia</a>
    {% endif %}
    {% endif %}
</section>

{% if noticia_list %}

<section class="lista-de-cards">
    {% for noticia in noticia_list %}
    <br>
        <article class="curriculo-card">
            <div class="retrato">
                <a href="{% url 'noticias:detail' noticia.id %}"><img src="{{ noticia.poster_url }}" alt="Poster da noticia {{ noticia.name}}" height="150px" width="150px"></a>
            </div>
            <div class="curriculo-text"> 
                <h3 class = 'noticia-name'>{{ noticia.name }} ({{ noticia.release_date | date}})</h3>
                <p class = 'noticia-bio'>{{ noticia.descricao }}</p>
            </div>
        </article>
    <br>

    {% endfor %}
</section>

{% else %}
<p>Não foi encontrada nenhuma notícia.</p>
{% endif %}

{% endblock content %}

noticias/templates/noticias/search.html
{% extends 'base.html' %}

{% block title %}
Buscar notícia
{% endblock title %}

{% block content %}
<hr>
<h2>Busca de Notícias por Nome</h2>
<form action="{% url 'noticias:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if noticia_list %}
<section class="lista-de-cards">
    {% for noticia in noticia_list %}
    <article class="card">
        <img src="{{ noticia.poster_url }}" alt="Poster da Notícia {{ noticia.name}}" width="180" height="180">
        <a href="{% url 'noticias:detail' noticia.id %}">{{ noticia.name }}</a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma notícia para a busca.</p>
{% endif %}

{% endblock content %}

noticias/templates/noticias/update.html
{% extends 'base.html' %}

{% block title %}
Editar notícia
{% endblock title %}

{% block content %}
<h2>Atualizar Dados da notícia {{ noticia.name }} ({{ noticia.release_date | date}})</h2>

<form method="POST" action="{% url 'noticias:update' noticia.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}