curriculo/urls.py
from django.urls import path

from . import views

app_name = 'curriculo'

urlpatterns = [
    path('list', views.CurriculoListView.as_view(), name='list'),
    path('user_profile/<username>', views.get_user_profile, name='user_profile'),
    path('profile/<int:curriculo_id>/', views.curriculo_detail, name='profile'),
    path('update/<int:curriculo_id>/', views.update_curriculo, name='update'),
    path('search/', views.search_curriculo, name='search'),
]

poliempregos/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('propostas/', include('propostas.urls')),
    path('noticias/', include('noticias.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('curriculo/', include('curriculo.urls'))
]

propostas/urls.py
from django.urls import path

from . import views

app_name = 'propostas'
urlpatterns = [
    path('', views.list_propostas, name='index'),
    path('search/', views.search_propostas, name='search'),
    path('create/', views.create_propostas, name='create'),
    path('<int:propostas_id>/', views.detail_propostas, name='detail'),
    path('update/<int:propostas_id>/', views.update_propostas, name='update'),
    path('delete/<int:propostas_id>/', views.delete_propostas, name='delete'),
    path('empresa_profile/<username>', views.get_empresa_profile, name='empresa_profile'),
    path('inscrito/<int:id>', views.inscrito_add, name='inscrito_add'),
    path('<int:propostas_id>/inscritos', views.inscrito_list, name='inscrito_list'),
    path('inscricoes/<username>', views.propostas_inscrito_list, name='inscricoes'),
]

user/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #path('registration', registration,name='registration'),
    path('signup/',SignUp,name='signup'),
    path('signup/estudante', EstudanteSignUpView.as_view(), name='estudante_signup'),
    path('signup/empresa', EmpresaSignUpView.as_view(), name='empresa_signup'),
]

propostas/models.py
from django.db import models
from django.conf import settings
from user.models import Empresa, Estudante
from curriculo.models import Curriculo
from django.utils import timezone


class Propostas(models.Model):
    name = models.CharField(max_length=255) #name = name
    empresa = models.ForeignKey(Empresa,on_delete=models.CASCADE)
    descricao = models.TextField() #descricao = descricao
    logo_proposta = models.URLField(max_length=200) #logo_proposta = logo_proposta
    n_vagas = models.IntegerField() #numero de vagas disponíveis
    data_pub = models.DateTimeField(default=timezone.now)
    inscrito = models.ManyToManyField(Curriculo, default = None, blank = True)

    def __str__(self):
        return f'{self.name}'

# Create your models here.

propostas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from .models import Propostas
from django.contrib.auth.decorators import login_required, permission_required
from django.core.exceptions import PermissionDenied


from user.models import User, Estudante
from curriculo.models import Curriculo

@login_required
def detail_propostas(request, propostas_id):
    propostas = get_object_or_404(Propostas, pk=propostas_id)
    propostas_list = Propostas.objects.filter(empresa = propostas.empresa).exclude(id = propostas_id)
    #propostas_list = Propostas.objects.filter(empresa = p.empresa)
    ins = bool
    context = {'propostas': propostas, 'ins': ins, 'propostas_list': propostas_list}
    if request.user.is_estudante:
        curriculo = request.user.estudante.curriculo
        if propostas.inscrito.filter(id = request.user.estudante.curriculo.id).exists():
            ins = True
        context = {'propostas': propostas, 'ins': ins, 'curriculo':curriculo, 'propostas_list': propostas_list}
    return render(request, 'propostas/detail.html', context)

@login_required
def get_empresa_profile(request,username):
    user = User.objects.get(username=username)
    propostas_list = Propostas.objects.filter(empresa=user.empresa)
    #propostas_list = Propostas.objects.get(empresa=user.empresa)
    return render(request, 'propostas/empresa_profile.html', {"user":user, 'propostas_list': propostas_list})

@login_required
def list_propostas(request):
    propostas_list = Propostas.objects.all()
    context = {'propostas_list': propostas_list}
    return render(request, 'propostas/index.html', context)

@login_required
def search_propostas(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        propostas_list = Propostas.objects.filter(name__icontains=search_term)
        context = {"propostas_list": propostas_list}
    return render(request, 'propostas/search.html', context)

@login_required
@permission_required('propostas.add_propostas')
def create_propostas(request):
    if request.method == 'POST':
        propostas_name = request.POST['name']
        propostas_empresa = request.user.empresa
        propostas_descricao = request.POST['descricao']
        propostas_logo_proposta = request.POST['logo_proposta']
        propostas_n_vagas = request.POST['n_vagas']
        #propostas_data_pub = request.POST['data_pub']
        propostas = Propostas(name=propostas_name,
                       empresa = propostas_empresa,
                      descricao=propostas_descricao,
                      logo_proposta=propostas_logo_proposta,
                      n_vagas=int(propostas_n_vagas))#,
                      #data_pub=propostas_data_pub)
        propostas.save()
        return HttpResponseRedirect(
            reverse('propostas:detail', args=(propostas.id, )))
    else:
        return render(request, 'propostas/create.html', {})

@login_required
@permission_required('propostas.change_propostas')
def update_propostas(request, propostas_id):
    propostas = get_object_or_404(Propostas, pk=propostas_id)

    if not (propostas.empresa == request.user.empresa or request.user.is_superuser):
        raise PermissionDenied

    if request.method == "POST":
        propostas.name = request.POST['name']
        propostas_empresa = request.user.empresa
        propostas.descricao = request.POST['descricao']
        propostas_logo_proposta = request.POST['logo_proposta']
        propostas_n_vagas = request.POST['n_vagas']
        propostas.save()
        return HttpResponseRedirect(
            reverse('propostas:detail', args=(propostas.id, )))

    context = {'propostas': propostas}
    return render(request, 'propostas/update.html', context)

@login_required
@permission_required('propostas.delete_propostas')
def delete_propostas(request, propostas_id):
    propostas = get_object_or_404(Propostas, pk=propostas_id)

    if request.method == "POST":
        propostas.delete()
        return HttpResponseRedirect(reverse('propostas:index'))

    context = {'propostas': propostas}
    return render(request, 'propostas/delete.html', context)

def inscrito_add(request, id):
    propostas = get_object_or_404(Propostas, id = id)
    if request.user.is_estudante:
        if propostas.inscrito.filter(id = request.user.estudante.curriculo.id).exists():
            propostas.inscrito.remove(request.user.estudante.curriculo)

        else:
            propostas.inscrito.add(request.user.estudante.curriculo)


    return HttpResponseRedirect(reverse('propostas:index'))

def inscrito_list(request,propostas_id):
    propostas = get_object_or_404(Propostas, id = propostas_id)

    if request.user.is_estudante:
        raise PermissionDenied
    else:
        if not (request.user.is_superuser):
            if not (propostas.empresa == request.user.empresa):
                raise PermissionDenied

    i_list = Curriculo.objects.filter(propostas = propostas_id)
    context = {'propostas': propostas, 'i_list' : i_list}
    return render(request, 'propostas/inscrito_list.html', context)


def propostas_inscrito_list(request,username):
    user = User.objects.get(username=username)

    if request.user.is_empresa:
        raise PermissionDenied

    curriculo = Curriculo.objects.get(estudante=user.estudante) 

    p_list = Propostas.objects.filter(inscrito = curriculo.id)
    context = {'user':user, 'curriculo': curriculo, 'p_list' : p_list}
    return render(request, 'propostas/inscricoes.html', context)
# Create your views here.

#class InscritoCreateView(generic.CreateView):
   # model = Inscrito
   # template_name = 'propostas/create_inscrito.html'
    #success_url = reverse_lazy('propostas:inscritos')

propostas/templates/propostas/create.html
{% extends 'base.html' %}
{% block title %} Criar Proposta {% endblock %} | Poli-Empregos
{% block content %}
<hr>
<br>
<center>
    <div align="center" style="border: 5px; border-style: solid; border-color: #002292; width:60%;">
        <h2>Inserir Nova Proposta</h2>
        <form method="POST" action="{% url 'propostas:create' %}">
            {% csrf_token %}
            <p>
                <label for="id_name">Título:</label>
                <input type="text" name="name" id="id_name" />
            </p>
            <p>
                <label for="id_descricao">Texto:</label>
                <input type="text" name="descricao" id="id_descricao" />
            </p>
            <p>
                <label for="id_logo_proposta">Logo da Proposta:</label>
                <input type="url" name="logo_proposta" id="id_logo_proposta" />
            </p>
            <p>
                <label for="id_n_vagas">Número de Vagas:</label>
                <input type="number" name="n_vagas" id="id_n_vagas" />
            </p>
            <button type="submit">Criar</button>
        </form>
    </div>
</center>

{% endblock content %}

propostas/templates/propostas/delete.html
{% extends 'base.html' %}
{% block title %} Deletar Proposta {% endblock %} | Poli-Empregos
{% block content %}
<form action="{% url 'propostas:delete' propostas.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a proposta "{{ propostas.name }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

propostas/templates/propostas/detail.html
{% extends 'base.html' %}

{% block title %} {{ propostas.name }} {% endblock %} | Poli-Empregos

{% block content %}
<hr>
<h2 align="center">{{ propostas.name }}</h2>
<br>
<section class="dados-de-filme">
    <p align="center">
        <center>
            <img align="center" src="{{ propostas.logo_proposta }}" alt="Poster da proposta {{ propostas.name}}" height="400px" width="400px">
        </center>
    </p>
    <br>
    <p>
        <ul style="list-style-type: none">
            <div class="proposta-edit">
                {% if propostas.empresa == request.user.empresa %}
                <a class='button' href="{% url 'propostas:update' propostas.id %}">Editar</a>
                {% endif %}
                <li align="right"><i>Data: {{ propostas.data_pub }}</i></li>
            </div>
            <hr>
            <br>
            <li align="justify"><b>Descrição:</b> {{ propostas.descricao }} </li>
            <br>
            <li><b align="center">Número de vagas:</b> {{ propostas.n_vagas }} </li>
            <br>
            
            <div class="proposta-list-top">
                {% if propostas.empresa == request.user.empresa %}
                <a class='button' href="{% url 'propostas:inscrito_list' propostas.id %}">Inscritos</a>
                <a class='button' href="{% url 'propostas:delete' propostas.id %}">Apagar</a>
                
            {% endif %} 
            </div>
        </ul>
    </p>

</section>
{% if request.user.is_estudante %}
    {% if ins %}
        <center>
            <button>
                <a href="{% url 'propostas:inscrito_add' propostas.id %}" style="color:white">Desinscrever-se</a>
            </button> 
        </center>
       
    {% else %}
    <center>
        <button>
            <a href="{% url 'propostas:inscrito_add' propostas.id %}" style="color:white">Inscrever-se</a> 
        </button> 
    </center>
    {% endif %}
{% endif %}
<hr>
<h2>Outras Propostas da Empresa</h2>
{% if propostas_list %}
<section class="lista-de-propostas">
    {% for propostas in propostas_list %}
    <article class="small-card">
        <img src="{{ propostas.logo_proposta }}"alt="Poster da Proposta {{ propostas.name}}">
        <a href="{% url 'propostas:detail' propostas.id %}">{{ propostas.name }}</a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma proposta da empresa.</p>
{% endif %}

{% endblock content %}

propostas/templates/propostas/empresa_profile.html
{% extends 'base.html' %}
{% block title %} Minhas Propostas {% endblock %} | Poli-Empregos
{% block content %}
<hr>
<br>
<h2>Minhas Propostas</h2>
<br>
<a class='button' href="{% url 'propostas:create' %}">Nova Proposta</a>

{% if propostas_list %}
<section class="lista-de-cards">
    {% for propostas in propostas_list %}
    <article class="card" align="center" style="border: 5px; border-style: solid ;color: #002292; border-color: #002292">
        <img src="{{ propostas.logo_proposta }}"alt="Poster da Proposta {{ propostas.name}}" height="150px" width="150px">
        <a href="{% url 'propostas:detail' propostas.id %}"><b>{{ propostas.name }}</b></a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma proposta.</p>
{% endif %}

{% endblock content %}

propostas/templates/propostas/index.html
{% extends 'base.html' %}
{% block title %} Propostas {% endblock %} | Poli-Empregos

{% block content %}
<br>
<section class="curriculo-list-top">
    <a class='button' href="{% url 'propostas:search' %}">Buscar Propostas</a>
    <br>
    {% if request.user.is_empresa %} 
        <a class='button' href="{% url 'propostas:empresa_profile' user.username %}">Minhas Propostas</a>
    {% endif %}
    {% if request.user.is_estudante %} 
        <a class='button' href="{% url 'propostas:inscricoes' user.username %}">Minhas Inscrições</a>
    {% endif %}
</section>
{% if propostas_list %}
<section class="lista-de-cards">
    {% for propostas in propostas_list %}
    <article class="card" style="border: 5px; border-style: solid ;color: #002292; border-color: #002292">
        <div>
            <a href="{% url 'propostas:detail' forloop.counter %}"><img src="{{ propostas.logo_proposta }}" height="150px" width="150px"
                alt="Poster da Proposta {{ propostas.name}}"></a>
        </div>
        <div>
            <p align="center"><b>{{ propostas.name }}</b></p>
        </div>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma proposta.</p>
{% endif %}

{% endblock content %}

propostas/templates/propostas/inscricoes.html
{% extends 'base.html' %}
{% block title %} Inscrições {% endblock %} | Poli-Empregos
{% block content %}
<hr>
<br>
<h2> Minhas inscrições</h2>
<br>
{% if p_list %}
<section class="lista-de-cards">
    {% for propostas in p_list %}
    <article class="card">
            <img src="{{ propostas.logo_proposta }}"
            alt="Poster da Proposta {{ propostas.name}}">
        <a href="{% url 'propostas:detail' propostas.id %}">{{ propostas.name }}</a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma proposta.</p>
{% endif %}

{% endblock content %}

propostas/templates/propostas/inscrito_list.html
{% extends 'base.html' %}
{% block title %} Lista de Inscritos {% endblock %} | Poli-Empregos
{% block content %}

{% if i_list %}
{% for curriculo in i_list %}
<hr>
<br>
<h2>
    Inscritos em {{propostas.name}}
</h2>
<br>
    <article class="curriculo-card">
        {% if curriculo.foto %}
        <img class= 'retrato' src="{{ curriculo.foto }}" alt="Nome de Estudante {{ curriculo.estudante}}" width="180" height="180">
        {% endif %}
        <div class="curriculo-text"> 
            <a class = 'curriculo-name' href="{% url 'curriculo:profile' curriculo.id %}">{{ curriculo.estudante.name }}</a>
            {% if curriculo.bio %}
            <p class = 'curriculo-bio'>{{ curriculo.bio }}</p>
            {% endif %}
        </div>
    </article>
{% endfor %}
{% else %}
<hr>
<br>
<h3>Ninguém incrito ainda</h3>
{% endif %}
{% endblock content %}

propostas/templates/propostas/search.html
{% extends 'base.html' %}
{% block title %} Busca por Propostas {% endblock %} | Poli-Empregos
{% block content %}
<hr>
<br>
<center>
    <div align="center" style="border: 5px; border-style: solid ; border-color: #002292; width:60%;">
        <h2>Busca de Propostas por Nome</h2>
        <form action="{% url 'propostas:search' %}">
            <p>
                <label for="id_query">Título:</label>
                <input type="text" name="query" id="id_query" />
            </p>
            <button type="submit">Buscar</button>
        </form>
    </div>
</center>

<h2>Resultado da Busca</h2>
{% if propostas_list %}
<section class="lista-de-cards">
    {% for propostas in propostas_list %}
    <article class="card">
        <img src="{{ propostas.logo_proposta }}" alt="Poster da proposta {{ propostas.name}}" height="150px" width="150px">
        <a href="{% url 'propostas:detail' propostas.id %}">{{ propostas.name }}</a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma proposta para a busca.</p>
{% endif %}

{% endblock content %}

propostas/templates/propostas/update.html
{% extends 'base.html' %}
{% block title %} Atualizar Proposta {% endblock %} | Poli-Empregos
{% block content %}

<center>
    <div align="center" style="border: 5px; border-style: solid ;color: #002292; border-color: #002292; width:60%;">
        <h2>Atualizar Dados da Proposta: {{ propostas.name }}</h2>
        <form method="POST" action="{% url 'propostas:update' propostas.id%}">
            {% csrf_token %}
            <p>
                <label for="id_name">Título:</label>
                <input type="text" name="name" id="id_name" value="{{ propostas.name }}" />
            </p>
            <p>
                <label for=" id_descricao">Descrição:</label>
                <input type="text" name="descricao" id="id_descricao" value="{{ propostas.descricao }}" />
            </p>
            <p>
                <label for=" id_logo_proposta">URL da logo da Proposta:</label>
                <input type="url" name="logo_proposta" id="id_logo_proposta" value="{{propostas.logo_proposta}}" />
            </p>
            <p>
                <label for="id_n_vagas">Número de Vagas:</label>
                <input type="integer" name="n_vagas" id="id_n_vagas" />
            </p>
            <button type="submit">Atualizar</button>
        </form>
    </div>
</center>

{% endblock content %}